### ISSUE TITLE
State logic in serial communications

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-shaq#20]
https://github.com/ut-robotics/picr21-team-shaq/blob/8ae20e5501d61d2b16a69e7d05405c0ee861823d/src/comm.py#L31-L38

https://github.com/ut-robotics/picr21-team-shaq/blob/8ae20e5501d61d2b16a69e7d05405c0ee861823d/src/comm.py#L51-L55

Why is there state handling logic inside the serial communications module? Should it not just be responsible for sending data to the mainboard? This state logic duplicates code that can be handled by the main files state machine.

**Comment by NikitaNaumov98** [comment]
I moved this logic away from communications.py file (changes are currently on my branch 'nikita', not in 'main'), but I receive 'serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)' on line 19 when trying to use new variant (old one works fine)
