### ISSUE TITLE
Convoluted way of using serial communications as thread

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-shaq#30]
https://github.com/ut-robotics/picr21-team-shaq/blob/8ae20e5501d61d2b16a69e7d05405c0ee861823d/src/main.py#L36
Currently the mainboard communications is implemented as a separate thread. This itself is fine.

What is weird is how it is implemented.

You need to set not only the speed but also the state of this Communication() object to configure anything, it seems.

Why not instead have a queue system where you push states into a buffer of that object and it consumes them one at a time. When there are no commands to process, the robot just stands still? This removes the need to have state handling logic in that thread. Also reduce the send rate of that thread, it should run at most 2x the image processing rate since new commands are generated with the speed of the image processor main loop.

Another solution would be to have a method push_last() command that pushes the last command sent to the Communications object to the mainboard.

https://github.com/ut-robotics/picr21-team-shaq/blob/8ae20e5501d61d2b16a69e7d05405c0ee861823d/src/main.py#L70-L71

**Comment by Tsapu** [comment]
The state of the communication module has been removed. The way the speeds are changed (changing the class variable) remains, I hope that's not too big of an issue. Not perfectly optimised performance, but it's not that critical.
