### ISSUE TITLE
Don't create separate code/files for tasks

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-shaq#53]
https://github.com/ut-robotics/picr21-team-shaq/blob/4a55a202eb090c13c86e718c11b7f69319990997/src/yl1.py#L1

https://github.com/ut-robotics/picr21-team-shaq/blob/4a55a202eb090c13c86e718c11b7f69319990997/src/yl2.py#L1

Tasks should be presented with the main robot code. Tasks are meant as steps that guide you through writing the robot's code. Code for new tasks should be written on top of the existing code.

**Comment by Tsapu** [comment]
Affirmative
